(()=>{
const API_TIMEOUT=12000,UPLOAD_TIMEOUT=180000;
async function timedFetch(url,opts={},ms=API_TIMEOUT){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),ms);try{return await fetch(url,{...opts,signal:opts.signal||ctrl.signal})}finally{clearTimeout(timer)}}
login=async function(email,password){const r=await timedFetch(BASE+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email:email.trim().toLowerCase(),password})});const d=await parseRes(r);saveSession({access_token:d.access_token,refresh_token:d.refresh_token,expires_at:Date.now()+((d.expires_in||3600)*1000),user:d.user});return session};
refreshSession=async function(){if(!session?.refresh_token)return null;try{const r=await timedFetch(BASE+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});const d=await parseRes(r);saveSession({access_token:d.access_token,refresh_token:d.refresh_token||session.refresh_token,expires_at:Date.now()+((d.expires_in||3600)*1000),user:d.user||session.user});return session}catch{saveSession(null);return null}};
api=async function(path,{method='GET',body=null,prefer=null,retry=true,headersExtra={}}={}){await ensureSession();const h={...headers(body!==null),...headersExtra};if(prefer)h.Prefer=prefer;let r;try{r=await timedFetch(BASE+path,{method,headers:h,body:body===null?undefined:(typeof body==='string'?body:JSON.stringify(body))},API_TIMEOUT)}catch(e){if(e?.name==='AbortError')throw Error('مهلت اتصال تمام شد. اینترنت یا دسترسی Supabase را بررسی کن.');throw e}if(r.status===401&&retry&&await refreshSession())return api(path,{method,body,prefer,retry:false,headersExtra});return parseRes(r)};
storageUpload=async function(path,blob,type,bucket=BUCKET){await ensureSession();let r;try{r=await timedFetch(BASE+'/storage/v1/object/'+bucket+'/'+path.split('/').map(encodeURIComponent).join('/'),{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+session.access_token,'Content-Type':type||blob.type||'application/octet-stream','x-upsert':'false'},body:blob},UPLOAD_TIMEOUT)}catch(e){if(e?.name==='AbortError')throw Error('آپلود بیش از حد طول کشید و متوقف شد.');throw e}return parseRes(r)};
async function copyText(text){try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return true}}catch{}try{const ta=document.createElement('textarea');ta.value=text;ta.setAttribute('readonly','');ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();return ok}catch{return false}}
makeSnapshot=async function(){return api('/rest/v1/rpc/get_admin_catalog_snapshot',{method:'POST',body:{}})};
serverBackup=async function(reason='manual'){return api('/rest/v1/rpc/create_catalog_backup',{method:'POST',body:{p_reason:String(reason||'manual').slice(0,120)}})};
bulkPrice=async function(sign){if(!selected.size)return;const pct=Math.abs(Number($('#bulkPct').value||0));if(!pct)return alert('درصد را وارد کن.');if(!confirm(`قیمت ${selected.size} محصول ${sign>0?'افزایش':'کاهش'} پیدا کند؟`))return;try{await serverBackup('before_bulk_price_change');await api('/rest/v1/rpc/bulk_adjust_product_prices',{method:'POST',body:{p_ids:[...selected],p_percent:sign*pct}});await loadData();alert('انجام شد')}catch(e){alert('عملیات انجام نشد: '+e.message)}};
bulkPublish=async function(v){if(!selected.size)return;try{await serverBackup(v?'before_bulk_publish':'before_bulk_draft');await api('/rest/v1/rpc/bulk_set_product_published',{method:'POST',body:{p_ids:[...selected],p_value:!!v}});await loadData()}catch(e){alert('عملیات انجام نشد: '+e.message)}};
$('#bulkUp').onclick=()=>bulkPrice(1);$('#bulkDown').onclick=()=>bulkPrice(-1);$('#bulkPublish').onclick=()=>bulkPublish(true);$('#bulkDraft').onclick=()=>bulkPublish(false);
optimizeImage=async function(file){let bmp=null,url=null,img=null,w,h,drawSource;try{if(window.createImageBitmap){bmp=await createImageBitmap(file);w=bmp.width;h=bmp.height;drawSource=bmp}else{url=URL.createObjectURL(file);img=new Image();img.src=url;await img.decode();w=img.naturalWidth;h=img.naturalHeight;drawSource=img}if(!w||!h)throw Error('ابعاد تصویر معتبر نیست');if(w*h>50000000)throw Error('رزولوشن تصویر خیلی بالاست؛ قبل از آپلود کوچک‌ترش کن');const max=1800,scale=Math.min(1,max/Math.max(w,h)),cw=Math.max(1,Math.round(w*scale)),ch=Math.max(1,Math.round(h*scale)),canvas=document.createElement('canvas');canvas.width=cw;canvas.height=ch;const ctx=canvas.getContext('2d');if(!ctx)throw Error('مرورگر امکان پردازش تصویر را ندارد');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.clearRect(0,0,cw,ch);ctx.drawImage(drawSource,0,0,cw,ch);const blob=await new Promise(res=>canvas.toBlob(res,'image/webp',.86));if(!blob)throw Error('WebP ساخته نشد');return blob}finally{bmp?.close?.();if(url)URL.revokeObjectURL(url)}};
uploadFiles=async function(files){if(!current?.id)return alert('اول محصول را ذخیره کن.');let order=Math.max(-1,...currentMedia.map(m=>Number(m.sort_order)||0))+1,hasVisibleImage=currentMedia.some(m=>m.media_type==='image'&&m.is_visible!==false),failed=0;for(const file of files){let publicPaths=[],privatePaths=[];try{if(file.size>50*1024*1024)throw Error('فایل بیشتر از ۵۰MB است');msg($('#uploadMsg'),'در حال پردازش '+file.name+'…');const stamp=Date.now()+'-'+Math.random().toString(36).slice(2,7);if(file.type.startsWith('image/')){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('فرمت تصویر پشتیبانی نمی‌شود');const original='originals/'+safeName(current.code)+'/'+stamp+'-'+safeName(file.name),optimized='products/'+safeName(current.code)+'/'+stamp+'.webp';await storageUpload(original,file,file.type,ORIGINAL_BUCKET);privatePaths.push(original);const webp=await optimizeImage(file);await storageUpload(optimized,webp,'image/webp');publicPaths.push(optimized);const makeFeatured=!hasVisibleImage;await api('/rest/v1/product_media',{method:'POST',body:{product_id:current.id,media_type:'image',storage_path:optimized,original_storage_path:original,sort_order:order++,is_visible:true,is_featured:makeFeatured},prefer:'return=minimal'});hasVisibleImage=true;publicPaths=[];privatePaths=[]}else if(file.type==='video/mp4'){const path='products/'+safeName(current.code)+'/'+stamp+'-'+safeName(file.name);await storageUpload(path,file,'video/mp4');publicPaths.push(path);await api('/rest/v1/product_media',{method:'POST',body:{product_id:current.id,media_type:'video',storage_path:path,sort_order:order++,is_visible:true,is_featured:false},prefer:'return=minimal'});publicPaths=[]}else throw Error('فقط JPG/PNG/WebP/MP4 مجاز است')}catch(err){failed++;if(publicPaths.length)await storageRemove(publicPaths).catch(()=>{});if(privatePaths.length)await storageRemove(privatePaths,ORIGINAL_BUCKET).catch(()=>{});msg($('#uploadMsg'),file.name+': '+err.message,'err');continue}}await loadData();current=products.find(p=>p.id===current.id)||current;currentMedia=media.filter(m=>m.product_id===current.id).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));renderMedia();msg($('#uploadMsg'),failed?`آپلود تمام شد؛ ${failed} فایل خطا داشت`:'آپلود و بهینه‌سازی تمام شد',failed?'err':'ok')};
$('#mediaInput').onchange=e=>{const files=[...e.target.files];e.target.value='';if(files.length)uploadFiles(files)};
syncMediaOrder=async function(){if(!current?.id)return;await api('/rest/v1/rpc/reorder_product_media',{method:'POST',body:{p_product_id:current.id,p_ids:currentMedia.map(m=>m.id)}});currentMedia.forEach((m,i)=>m.sort_order=i);renderMedia()};
setFeatured=async function(id){if(!current?.id)return;try{await api('/rest/v1/rpc/set_product_featured_media',{method:'POST',body:{p_product_id:current.id,p_media_id:id}});currentMedia.forEach(m=>{if(m.media_type==='image')m.is_featured=m.id===id});renderMedia()}catch(e){alert('Featured تغییر نکرد: '+e.message)}};
toggleMedia=async function(id){const m=currentMedia.find(x=>x.id===id);if(!m)return;try{await api('/rest/v1/rpc/set_product_media_visibility',{method:'POST',body:{p_media_id:id,p_visible:!m.is_visible}});await loadData();current=products.find(p=>p.id===current.id)||current;currentMedia=media.filter(x=>x.product_id===current.id).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));renderMedia()}catch(e){alert('وضعیت رسانه تغییر نکرد: '+e.message)}};
deleteMedia=async function(id){const m=currentMedia.find(x=>x.id===id);if(!m||!confirm('فایل و رکورد رسانه برای همیشه حذف شود؟'))return;try{await serverBackup('before_media_hard_delete');const publicPaths=[m.storage_path,m.poster_path].filter(Boolean),privatePaths=[m.original_storage_path].filter(Boolean);await api('/rest/v1/product_media?id=eq.'+encodeURIComponent(id),{method:'DELETE',prefer:'return=minimal'});let cleanupFailed=false;if(publicPaths.length)await storageRemove(publicPaths).catch(()=>{cleanupFailed=true});if(privatePaths.length)await storageRemove(privatePaths,ORIGINAL_BUCKET).catch(()=>{cleanupFailed=true});await loadData();current=products.find(p=>p.id===current.id)||current;currentMedia=media.filter(x=>x.product_id===current.id).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));if(currentMedia.length)await syncMediaOrder();const imgs=currentMedia.filter(x=>x.media_type==='image'&&x.is_visible!==false);if(imgs.length&&!imgs.some(x=>x.is_featured))await setFeatured(imgs[0].id);renderMedia();if(cleanupFailed)alert('رکورد حذف شد، ولی پاک‌سازی یکی از فایل‌های Storage کامل نشد؛ در چک سلامت مشخص می‌شود.')}catch(e){alert('حذف انجام نشد: '+e.message)}};
loadAnalytics=async function(){try{const d=await api('/rest/v1/rpc/get_admin_analytics',{method:'POST',body:{p_days:30}}),views=Number(d?.product_views||0),orders=Number(d?.order_clicks||0),conv=views?Math.round(orders/views*100):0;$('#statGrid').innerHTML=[['بازدید کاتالوگ',d?.catalog_views||0],['بازدید محصول',views],['کلیک سفارش',orders],['اشتراک‌گذاری',d?.shares||0],['نرخ تبدیل',conv+'٪']].map(x=>`<div class="stat"><b>${fa(x[1])}</b><small>${x[0]}</small></div>`).join('');renderBars($('#topProducts'),(d?.top_products||[]).map(x=>[x.key,Number(x.count)]));renderBars($('#topSearches'),(d?.top_searches||[]).map(x=>[x.key,Number(x.count)]))}catch(e){$('#statGrid').innerHTML='<div class="err small">'+esc(e.message)+'</div>'}};
async function getBackupSnapshot(id){const x=await api('/rest/v1/catalog_backups?select=snapshot&id=eq.'+encodeURIComponent(id)+'&limit=1');if(!x?.[0]?.snapshot)throw Error('بکاپ پیدا نشد');return x[0].snapshot}
renderBackups=async function(){let b=[];try{b=await api('/rest/v1/catalog_backups?select=id,reason,created_at&order=created_at.desc&limit=30')}catch(e){$('#backupList').innerHTML='<div class="err small">'+esc(e.message)+'</div>';return}$('#backupList').innerHTML=b.map(x=>`<div class="backup"><div><b>${esc(x.reason)}</b><div class="meta">${new Date(x.created_at).toLocaleString('fa-IR')}</div></div><div class="actions"><button class="btn sm" data-dl="${x.id}">دانلود</button><button class="btn sm" data-restore="${x.id}">بازیابی ادغامی</button><button class="btn danger sm" data-rmb="${x.id}">حذف بکاپ</button></div></div>`).join('')||'<div class="muted small" style="padding:16px">هنوز بکاپی نیست.</div>';$$('[data-dl]').forEach(btn=>btn.onclick=async()=>{try{downloadJson(await getBackupSnapshot(btn.dataset.dl),'modland-backup-'+new Date().toISOString().slice(0,10)+'.json')}catch(e){alert(e.message)}});$$('[data-restore]').forEach(btn=>btn.onclick=async()=>{try{await restoreSnapshot(await getBackupSnapshot(btn.dataset.restore))}catch(e){alert(e.message)}});$$('[data-rmb]').forEach(btn=>btn.onclick=async()=>{if(confirm('این بکاپ حذف شود؟')){await api('/rest/v1/catalog_backups?id=eq.'+encodeURIComponent(btn.dataset.rmb),{method:'DELETE',prefer:'return=minimal'});renderBackups()}})};
restoreSnapshot=async function(snap){if(!snap||!confirm('بازیابی ادغامی انجام شود؟ قبل از آن بکاپ فعلی ساخته می‌شود. داده‌های بکاپ در یک تراکنش Merge می‌شوند.'))return;try{await serverBackup('before_restore');await api('/rest/v1/rpc/restore_catalog_snapshot',{method:'POST',body:{p_snapshot:snap}});await loadData();alert('بازیابی کامل و اتمیک انجام شد')}catch(e){alert('خطای بازیابی: '+e.message)}};
$('#makeBackup').onclick=async()=>{try{await serverBackup('manual');await renderBackups();alert('بکاپ سرور ساخته شد')}catch(e){alert('بکاپ ساخته نشد: '+e.message)}};
$('#downloadCurrent').onclick=async()=>{try{downloadJson(await makeSnapshot(),'modland-backup-'+new Date().toISOString().slice(0,10)+'.json')}catch(e){alert(e.message)}};
$('#copyProductLink').onclick=async()=>{const code=$('#productForm').elements.code.value.trim();if(!code)return;const ok=await copyText(CATALOG_URL+'product.html?code='+encodeURIComponent(code));msg($('#productMsg'),ok?'لینک مشتری کپی شد':'کپی لینک انجام نشد',ok?'ok':'err')};

$('#productForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,id=f.elements.id.value;const body={code:f.elements.code.value.trim(),name:f.elements.name.value.trim(),brand:f.elements.brand.value.trim()||null,category_id:f.elements.category_id.value||null,price_toman:f.elements.price_toman.value?Number(f.elements.price_toman.value):null,old_price_toman:f.elements.old_price_toman.value?Number(f.elements.old_price_toman.value):null,sizes:f.elements.sizes.value.split(',').map(x=>x.trim()).filter(Boolean),stock_status:f.elements.stock_status.value.trim()||'موجود',stock_note:f.elements.stock_note.value.trim()||null,badge:f.elements.badge.value.trim()||null,is_featured:!!f.elements.is_featured?.checked,sort_order:Number(f.elements.sort_order.value||0),shipping_text:f.elements.shipping_text.value.trim()||null,order_button:f.elements.order_button.value.trim()||null,order_message:f.elements.order_message.value.trim()||null,description:f.elements.description.value.trim()||null,features:f.elements.features.value.split('\n').map(x=>x.trim()).filter(Boolean),size_guide:f.elements.size_guide.value.trim()||null,is_published:f.elements.is_published.checked};try{msg($('#productMsg'),'در حال ذخیره…');let d;if(id)d=await api('/rest/v1/products?id=eq.'+encodeURIComponent(id),{method:'PATCH',body,prefer:'return=representation'});else d=await api('/rest/v1/products',{method:'POST',body,prefer:'return=representation'});current=(d||[])[0]||current;formVal(f,'id',current?.id||id);await loadData();if(current?.id){current=products.find(x=>x.id===current.id)||current;currentMedia=media.filter(m=>m.product_id===current.id).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));renderMedia()}msg($('#productMsg'),'ذخیره شد','ok')}catch(err){msg($('#productMsg'),err.message,'err')}};

function setupIOSAdminInstall(){const b=$('#iosInstallAdmin');if(!b)return;const ios=/iphone|ipad|ipod/i.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1),standalone=window.matchMedia?.('(display-mode: standalone)').matches||navigator.standalone===true;if(ios&&!standalone){b.hidden=false;b.onclick=()=>alert('برای نصب پنل مدیریت در Safari روی Share بزن و Add to Home Screen را انتخاب کن.')}else b.hidden=true}
previewHtml=function(p){const mm=media.filter(m=>m.product_id===p.id&&m.media_type!=='video'&&m.is_visible!==false).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)),img=publicUrl(mm.find(m=>m.is_featured)||mm[0]);return `<!doctype html><html lang="fa" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;background:#09090b;color:#f7f2e8;font-family:Tahoma;padding:16px}main{max-width:540px;margin:auto}.c{background:#141416;border:1px solid #332f26;border-radius:22px;overflow:hidden}.c img{width:100%;aspect-ratio:3/4;object-fit:cover}.b{padding:16px}h1{font-size:22px}strong{color:#f0d36b;font-size:20px}.m{color:#aaa7a0;line-height:2;font-size:12px}</style><main><div class="c">${img?`<img src="${esc(img)}" alt="${esc(p.name)}">`:''}<div class="b"><h1>${esc(p.name)}</h1><div class="m">${esc(p.brand||'')} · کد ${esc(p.code)}</div><p><strong>${money(p.price_toman)}</strong></p><div class="m">${esc(p.description||'')}</div></div></div></main></html>`};
setupIOSAdminInstall();
})();