(()=>{
const ADMIN_SESSION='modland_admin_session_v3';
function idle(fn){if('requestIdleCallback'in window)requestIdleCallback(fn,{timeout:1200});else setTimeout(fn,0)}
function adminSid(){try{return (session?.user?.id||'admin').toString().slice(0,80)}catch{return'admin'}}
function reportAdminError(message,context={}){idle(()=>fetch(BASE+'/rest/v1/rpc/report_app_error',{method:'POST',headers:headers(),body:JSON.stringify({p_source:'admin',p_message:String(message||'unknown error').slice(0,1000),p_context:context,p_session_id:adminSid()}),keepalive:true}).catch(()=>{}))}
window.addEventListener('error',e=>reportAdminError(e.message,{file:e.filename?.split('/').pop(),line:e.lineno,col:e.colno}));window.addEventListener('unhandledrejection',e=>reportAdminError(e.reason?.message||String(e.reason||'unhandled rejection'),{type:'promise'}));
function installFeaturedField(){const f=$('#productForm');if(!f||f.elements.is_featured)return;const badge=f.elements.badge?.closest('label');if(!badge)return;badge.insertAdjacentHTML('afterend','<label class="field"><span>کالکشن ویژه</span><label class="row"><input name="is_featured" type="checkbox"> پیشنهاد MODLAND</label></label>')}
installFeaturedField();
const baseOpenProduct=openProduct;openProduct=function(id=null){baseOpenProduct(id);installFeaturedField();formVal($('#productForm'),'is_featured',!!current?.is_featured)};
const baseRenderProducts=renderProducts;renderProducts=function(){baseRenderProducts();document.querySelectorAll('[data-edit]').forEach(btn=>{const p=products.find(x=>x.id===btn.dataset.edit);if(!p?.is_featured)return;const item=btn.closest('.item'),meta=item?.querySelector('.meta');if(meta&&!meta.textContent.includes('پیشنهاد MODLAND'))meta.textContent+=' · پیشنهاد MODLAND'})};
function installHistoryUI(){if(document.querySelector('[data-tab="history"]'))return;const nav=document.querySelector('.tabs'),backups=$('#backups');if(!nav||!backups)return;const tab=document.createElement('button');tab.className='tab';tab.dataset.tab='history';tab.textContent='تاریخچه/Undo';const storeTab=nav.querySelector('[data-tab="store"]');nav.insertBefore(tab,storeTab||null);const sec=document.createElement('section');sec.id='history';sec.className='hide';sec.innerHTML=`<div class="card"><div class="row between wraprow"><div><b>تاریخچه تغییرات</b><div class="muted small">Undo فقط روی جدیدترین عملیات امن است؛ تغییرات یک تراکنش با هم برمی‌گردند.</div></div><button id="refreshHistory" class="btn sm">بروزرسانی</button></div><div id="historyList"></div></div><div class="card"><div class="row between wraprow"><div><b>خطاهای ثبت‌شده</b><div class="muted small">خطاهای مشتری، صفحه محصول و پنل مدیریت</div></div><button id="clearOldErrors" class="btn sm">پاک‌کردن خطاهای قدیمی</button></div><div id="errorList"></div></div>`;backups.insertAdjacentElement('afterend',sec);tab.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');['products','analytics','backups','history','store','cats'].forEach(id=>$('#'+id)?.classList.toggle('hide',id!=='history'));loadHistory()};$$('.tab').filter(x=>x!==tab).forEach(t=>t.addEventListener('click',()=>sec.classList.add('hide')));$('#refreshHistory').onclick=loadHistory;$('#clearOldErrors').onclick=clearOldErrors}
installHistoryUI();
const entityLabel={products:'محصول',product_media:'رسانه',categories:'دسته',store_profile:'فروشگاه',catalog_preferences:'ظاهر'},actionLabel={INSERT:'ایجاد',UPDATE:'ویرایش',DELETE:'حذف'};
function groupLogs(logs){const groups=new Map;for(const x of logs){const key=x.transaction_id?`tx:${x.transaction_id}`:`id:${x.id}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(x)}return [...groups.values()].map(g=>g.sort((a,b)=>Number(b.sequence_no||0)-Number(a.sequence_no||0))).sort((a,b)=>Number(b[0].sequence_no||0)-Number(a[0].sequence_no||0))}
async function loadHistory(){try{const [logs,errs]=await Promise.all([api('/rest/v1/admin_activity_log?select=id,action,entity_type,entity_id,entity_code,created_at,undone_at,transaction_id,sequence_no&order=created_at.desc&limit=120'),api('/rest/v1/app_errors?select=id,source,message,created_at&order=created_at.desc&limit=40')]),groups=groupLogs(logs);$('#historyList').innerHTML=groups.length?groups.map(g=>{const x=g[0],undone=g.every(z=>z.undone_at),label=g.length>1?`عملیات گروهی · ${fa(g.length)} تغییر`:`${actionLabel[x.action]||x.action} ${entityLabel[x.entity_type]||x.entity_type}`,codes=[...new Set(g.map(z=>z.entity_code||z.entity_id).filter(Boolean))].slice(0,3).map(esc).join('، ');const irreversible=g.length===1&&x.entity_type==='product_media'&&x.action==='DELETE';return `<div class="backup"><div><b>${label}</b><div class="meta">${codes||'—'} · ${new Date(x.created_at).toLocaleString('fa-IR')}${undone?' · Undo شده':''}${irreversible?' · فایل Storage حذف دائمی شده':''}</div></div><div class="actions">${!undone&&!irreversible?`<button class="btn sm" data-undo="${x.id}">Undo</button>`:undone?'<span class="muted small">برگردانده شد</span>':'<span class="muted small">غیرقابل Undo</span>'}</div></div>`}).join(''):'<div class="muted small" style="padding:16px">هنوز تغییری ثبت نشده.</div>';document.querySelectorAll('[data-undo]').forEach(b=>b.onclick=()=>undoLog(b.dataset.undo));$('#errorList').innerHTML=errs.length?errs.map(x=>`<div class="backup"><div><b>${esc(x.source)}</b><div class="meta">${new Date(x.created_at).toLocaleString('fa-IR')}</div><div class="small" style="margin-top:5px;direction:ltr;text-align:left;word-break:break-word">${esc(x.message)}</div></div></div>`).join(''):'<div class="muted small" style="padding:16px">خطای ثبت‌شده‌ای وجود ندارد.</div>'}catch(err){reportAdminError(err.message,{stage:'load_history'});$('#historyList').innerHTML='<div class="err small" style="padding:16px">'+esc(err.message)+'</div>'}}
function undoMessage(m){if(/newer changes/i.test(m))return'این عملیات قدیمی‌تر از تغییرات بعدی است. اول جدیدترین تغییر همان مورد را Undo کن.';if(/newer media/i.test(m))return'برای رسانه‌های این محصول تغییر جدیدتری وجود دارد؛ اول جدیدترین عملیات رسانه را Undo کن.';if(/category is used/i.test(m))return'این دسته الان توسط محصول استفاده می‌شود؛ اول وابستگی جدیدتر را تغییر بده.';return m}
async function undoLog(id){if(!confirm('این عملیات برگردانده شود؟ تغییرات هم‌تراکنش هم با هم Undo می‌شوند.'))return;try{await api('/rest/v1/rpc/undo_admin_activity',{method:'POST',body:{p_log_id:id},prefer:'return=minimal'});await loadData();await loadHistory();alert('تغییر با موفقیت برگردانده شد')}catch(err){reportAdminError(err.message,{stage:'undo'});alert('Undo انجام نشد: '+undoMessage(err.message))}}
async function clearOldErrors(){if(!confirm('خطاهای قدیمی‌تر از ۳۰ روز پاک شوند؟'))return;const cut=new Date(Date.now()-30*864e5).toISOString();try{await api('/rest/v1/app_errors?created_at=lt.'+encodeURIComponent(cut),{method:'DELETE',prefer:'return=minimal'});await loadHistory()}catch(err){reportAdminError(err.message,{stage:'clear_errors'});alert(err.message)}}
const originalShowApp=showApp;showApp=async function(){await originalShowApp();installFeaturedField();installHistoryUI();renderProducts()};
})();