const BASE='https://bemkwibdtjrvrstlmvca.supabase.co',KEY='sb_publishable_oqpsHvl6ty2aYmAkxwfwfw_pjsN8a6p',BUCKET='modland-media',CACHE='modland_snapshot_v8',OLD_CACHES=['modland_snapshot_v7','modland_snapshot_v6'],SESSION='modland_anon_session';
let data={store:null,prefs:null,categories:[],products:[],media:[],collections:{new:[],popular:[],discounts:[],featured:[]}},activeCat=null,term='',deferredInstall=null,lastTrackedSearch='',activeCollection=null,collectionTimer=null,cardObserver=null;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),fa=n=>String(n??'').replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[+d]),money=n=>n==null?'تماس بگیرید':fa(Number(n).toLocaleString('en-US'))+' تومان';
function idle(fn){if('requestIdleCallback'in window)requestIdleCallback(fn,{timeout:1200});else setTimeout(fn,0)}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2100)}
function sid(){let s=localStorage.getItem(SESSION);if(!s){s=(crypto.randomUUID?.()||Math.random().toString(36).slice(2))+Date.now().toString(36);localStorage.setItem(SESSION,s)}return s.slice(0,80)}
function postJson(path,body){return fetch(BASE+path,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(body),keepalive:true})}
function track(event_type,p=null,search_term=null){idle(()=>postJson('/rest/v1/catalog_events',{event_type,product_id:p?.id||null,product_code:p?.code||null,search_term:search_term?.slice(0,80)||null,session_id:sid(),page_path:location.pathname+location.search}).catch(()=>{}))}
function reportError(message,context={}){idle(()=>postJson('/rest/v1/rpc/report_app_error',{p_source:'catalog',p_message:String(message||'unknown error').slice(0,1000),p_context:context,p_session_id:sid()}).catch(()=>{}))}
window.addEventListener('error',e=>reportError(e.message,{file:e.filename?.split('/').pop(),line:e.lineno,col:e.colno}));window.addEventListener('unhandledrejection',e=>reportError(e.reason?.message||String(e.reason||'unhandled rejection'),{type:'promise'}));
function mediaUrl(m){if(!m)return'';const x=m.external_url||m.storage_path||'';if(/^https?:\/\//i.test(x))return x;return x?BASE+'/storage/v1/object/public/'+BUCKET+'/'+x.split('/').map(encodeURIComponent).join('/'):''}
function mediaFor(id){const a=(data.media||[]).filter(m=>m.product_id===id&&m.is_visible!==false).sort((x,y)=>(x.sort_order||0)-(y.sort_order||0)||String(x.id).localeCompare(String(y.id))),images=a.filter(m=>m.media_type!=='video');return{images,featured:images.find(m=>m.is_featured)||images[0]}}
function applyTheme(){const t=data.prefs?.theme||{};if(t.bg)document.documentElement.style.setProperty('--bg',t.bg);if(t.text)document.documentElement.style.setProperty('--text',t.text);if(t.muted)document.documentElement.style.setProperty('--muted',t.muted);if(t.accent)document.documentElement.style.setProperty('--gold',t.accent);if(t.accent2)document.documentElement.style.setProperty('--gold2',t.accent2);document.documentElement.style.setProperty('--cols',Number(t.galleryColumns)===1?'1':'2')}
function safeHttpUrl(v){try{const u=new URL(String(v||''),location.href);return /^https?:$/.test(u.protocol)?u.href:null}catch{return null}}
function hero(){const s=data.store||{},featuredIds=data.collections?.featured||[],p=(data.products||[]).find(x=>featuredIds.includes(x.id))||(data.products||[])[0],m=p?mediaFor(p.id).featured:null,u=mediaUrl(m),img=$('#heroImg');$('#watermark').textContent=s.watermark||'MODLAND.QESHM';$('#catalogTitle').textContent=s.catalog_title||s.store_name||'کاتالوگ مدلند';$('#tagline').textContent=s.tagline||'استایل خاص، انتخاب راحت، سفارش سریع';$('#countPill').textContent=fa(data.products.length)+' محصول';$('#shippingPill').textContent=s.footer_note||'ارسال رایگان';if(u&&img){img.fetchPriority='high';img.loading='eager';img.decoding='async';if(img.src!==u)img.src=u;img.hidden=false}else if(img)img.hidden=true}
function chips(){const cats=(data.categories||[]).filter(c=>c.is_visible!==false);$('#chips').innerHTML=`<button class="chip ${activeCat===null?'on':''}" data-cat="">همه · ${fa(data.products.length)}</button>`+cats.map(c=>`<button class="chip ${activeCat===c.id?'on':''}" data-cat="${esc(c.id)}">${esc(c.name)} · ${fa(data.products.filter(p=>p.category_id===c.id).length)}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{activeCat=b.dataset.cat||null;chips();renderCollections();renderProducts()})}
function saved(){try{return new Set(JSON.parse(localStorage.getItem('modland_saved')||'[]'))}catch{return new Set()}}
function toggleSaved(p){const s=saved();s.has(p.id)?s.delete(p.id):s.add(p.id);localStorage.setItem('modland_saved',JSON.stringify([...s]));track('favorite',p);renderProducts()}
function cardHtml(p,i=99,compact=false,sv=null){const m=mediaFor(p.id).featured,u=mediaUrl(m),off=p.old_price_toman&&p.price_toman&&p.old_price_toman>p.price_toman?Math.round((1-p.price_toman/p.old_price_toman)*100):null,load=i<2?'eager':'lazy',priority=i===0?'high':'auto';if(compact)return `<a class="collection-card" href="./product.html?code=${encodeURIComponent(p.code)}"><div class="collection-pic">${u?`<img src="${esc(u)}" alt="${esc(p.name)}" loading="lazy" decoding="async">`:''}${p.is_featured?'<span class="collection-mark">MODLAND PICK</span>':''}</div><div class="collection-copy"><b>${esc(p.name)}</b><span>${money(p.price_toman)}</span></div></a>`;return `<article class="card"><a href="./product.html?code=${encodeURIComponent(p.code)}" aria-label="${esc(p.name)}"><div class="pic">${u?`<img src="${esc(u)}" alt="${esc(p.name)}" loading="${load}" fetchpriority="${priority}" decoding="async">`:'<div class="empty">بدون تصویر</div>'}${p.badge?`<span class="badge">${esc(p.badge)}</span>`:''}</div><div class="card-body"><div class="title">${esc(p.name)}</div><div class="sub">${esc(p.brand||'MODLAND')} · کد ${esc(p.code)}</div><div class="price">${money(p.price_toman)}${p.old_price_toman?` <span class="old">${money(p.old_price_toman)}</span>`:''}${off?` <small>٪${fa(off)}</small>`:''}</div></div></a><button class="fav ${sv?.has(p.id)?'on':''}" data-fav="${p.id}" aria-label="علاقه‌مندی" aria-pressed="${sv?.has(p.id)||false}">♥</button></article>`}
function observeCards(){cardObserver?.disconnect?.();if(!('IntersectionObserver'in window)){document.querySelectorAll('.card').forEach(x=>x.classList.add('reveal'));return}cardObserver=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){x.target.classList.add('reveal');cardObserver.unobserve(x.target)}}),{rootMargin:'120px',threshold:.01});document.querySelectorAll('.card').forEach(x=>cardObserver.observe(x))}
function renderProducts(){const q=term.trim().toLowerCase(),sv=saved(),arr=(data.products||[]).filter(p=>(!activeCat||p.category_id===activeCat)&&(!q||[p.name,p.code,p.brand,p.description,p.badge].filter(Boolean).some(v=>String(v).toLowerCase().includes(q))));$('#resultCount').textContent=fa(arr.length)+' مورد';$('#empty').hidden=arr.length>0;$('#grid').innerHTML=arr.map((p,i)=>cardHtml(p,i,false,sv)).join('');document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const p=data.products.find(x=>x.id===b.dataset.fav);if(p)toggleSaved(p)});requestAnimationFrame(observeCards)}
const collectionLabels={featured:'پیشنهاد MODLAND',new:'جدیدها',popular:'محبوب‌ها',discounts:'تخفیف‌ها'};
function ensureCollections(){if($('#collectionsWrap'))return;const anchor=document.querySelector('.section-head');if(!anchor)return;anchor.insertAdjacentHTML('beforebegin','<section id="collectionsWrap" class="collections-wrap" hidden><div class="collections-head"><div><b>کالکشن‌ها</b><small>انتخاب‌های هوشمند MODLAND</small></div><div id="collectionDots" class="collection-dots"></div></div><div id="collectionTabs" class="collection-tabs"></div><div id="collectionRail" class="collection-rail"></div></section>')}
function availableCollections(){const c=data.collections||{},order=['featured','new','popular','discounts'];return order.filter(k=>Array.isArray(c[k])&&c[k].length)}
function restartCollectionTimer(){clearInterval(collectionTimer);const keys=availableCollections();if(keys.length<2||document.hidden||term.trim()||activeCat)return;collectionTimer=setInterval(()=>{const i=keys.indexOf(activeCollection);activeCollection=keys[(i+1)%keys.length];renderCollections(false)},6500)}
function renderCollections(restart=true){ensureCollections();const wrap=$('#collectionsWrap');if(!wrap)return;const keys=availableCollections();if(!keys.length||term.trim()||activeCat){wrap.hidden=true;clearInterval(collectionTimer);return}wrap.hidden=false;if(!activeCollection||!keys.includes(activeCollection))activeCollection=keys[0];$('#collectionTabs').innerHTML=keys.map(k=>`<button class="collection-tab ${activeCollection===k?'on':''}" data-collection="${k}">${collectionLabels[k]}</button>`).join('');$('#collectionDots').innerHTML=keys.map(k=>`<i class="${activeCollection===k?'on':''}"></i>`).join('');const ids=new Set(data.collections[activeCollection]||[]),products=(data.products||[]).filter(p=>ids.has(p.id));$('#collectionRail').innerHTML=products.map((p,i)=>cardHtml(p,i,true)).join('');document.querySelectorAll('[data-collection]').forEach(b=>b.onclick=()=>{activeCollection=b.dataset.collection;renderCollections(true)});if(restart)restartCollectionTimer()}
function contacts(){const s=data.store||{},links=[['اینستاگرام',safeHttpUrl(s.instagram_url)],['تلگرام',safeHttpUrl(s.telegram_url)],['روبیکا',safeHttpUrl(s.rubika_url)]].filter(x=>x[1]);$('#socials').innerHTML=links.map(([l,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${l}</a>`).join('');const phones=[['تماس ۱',s.phone1],['تماس ۲',s.phone2]].filter(x=>x[1]);if(phones.length||s.address){$('#contact').hidden=false;$('#phones').innerHTML=phones.map(([l,p])=>{const tel=String(p).replace(/[^+\d]/g,'');return `<a class="phone" href="tel:${esc(tel)}"><b>${esc(p)}</b><span>${l}</span></a>`}).join('');$('#address').textContent=s.address||''}else $('#contact').hidden=true;$('#footerNote').textContent=s.footer_note||'';$('#storeName').textContent=s.store_name||''}
function renderAll(){applyTheme();hero();chips();renderCollections();renderProducts();contacts()}
function normalizeSnapshot(d){return{store:d?.store||null,prefs:d?.prefs||null,categories:d?.categories||[],products:d?.products||[],media:d?.media||[],collections:d?.collections||{new:[],popular:[],discounts:[],featured:[]}}}
function cacheRead(){for(const key of [CACHE,...OLD_CACHES]){try{const c=JSON.parse(localStorage.getItem(key)||'null');if(c?.payload){data=normalizeSnapshot(c.payload);renderAll();$('#sync').textContent='نسخه ذخیره‌شده';return true}}catch{}}return false}
function cacheWrite(payload){try{localStorage.setItem(CACHE,JSON.stringify({at:Date.now(),payload}))}catch{}}
async function fetchSnapshot(){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),6000),started=performance.now();try{const r=await fetch(BASE+'/rest/v1/rpc/get_catalog_snapshot',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:'{}',cache:'no-store',signal:ctrl.signal});if(!r.ok)throw Error(await r.text());data=normalizeSnapshot(await r.json());cacheWrite(data);renderAll();$('#sync').textContent='به‌روز · '+Math.max(0,Math.round(performance.now()-started))+'ms';$('#offline').classList.remove('show')}catch(e){reportError(e.message,{stage:'snapshot',online:navigator.onLine});if(![CACHE,...OLD_CACHES].some(k=>localStorage.getItem(k)))$('#grid').innerHTML='<div class="empty" style="grid-column:1/-1">بارگذاری کاتالوگ انجام نشد. اتصال اینترنت را بررسی کنید و دوباره وارد شوید.</div>';$('#sync').textContent='حالت ذخیره‌شده';$('#offline').classList.add('show')}finally{clearTimeout(timer)}}
let st;$('#q').addEventListener('input',e=>{term=e.target.value;renderCollections();renderProducts();clearTimeout(st);st=setTimeout(()=>{const q=term.trim();if(q.length>=2&&q!==lastTrackedSearch){lastTrackedSearch=q;track('search',null,q)}},700)});
function isIOS(){return /iphone|ipad|ipod/i.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)}
function isStandalone(){return window.matchMedia?.('(display-mode: standalone)').matches||navigator.standalone===true}
function setupInstall(){const b=$('#install');if(!b)return;if(isIOS()&&!isStandalone()){b.textContent='نصب روی آیفون';b.classList.add('show');b.onclick=()=>toast('در Safari روی Share بزن و Add to Home Screen را انتخاب کن');return}window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;b.textContent='نصب کاتالوگ';b.classList.add('show')});b.onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;b.classList.remove('show')}}
window.addEventListener('online',fetchSnapshot);window.addEventListener('offline',()=>$('#offline').classList.add('show'));document.addEventListener('visibilitychange',()=>{if(document.hidden)clearInterval(collectionTimer);else restartCollectionTimer()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(e=>reportError(e.message,{stage:'sw'}));
setupInstall();const hadCache=cacheRead();if(!hadCache)renderAll();idle(()=>track('catalog_view'));fetchSnapshot();