const BASE='https://bemkwibdtjrvrstlmvca.supabase.co',KEY='sb_publishable_oqpsHvl6ty2aYmAkxwfwfw_pjsN8a6p',BUCKET='modland-media',CACHE='modland_snapshot_v6',SESSION='modland_anon_session';
let data={store:null,prefs:null,categories:[],products:[],media:[]},activeCat=null,term='',deferredInstall=null,lastTrackedSearch='';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),fa=n=>String(n??'').replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[+d]),money=n=>n==null?'تماس بگیرید':fa(Number(n).toLocaleString('en-US'))+' تومان';
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
function sid(){let s=localStorage.getItem(SESSION);if(!s){s=(crypto.randomUUID?.()||Math.random().toString(36).slice(2))+Date.now().toString(36);localStorage.setItem(SESSION,s)}return s.slice(0,80)}
function track(event_type,p=null,search_term=null){fetch(BASE+'/rest/v1/catalog_events',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({event_type,product_id:p?.id||null,product_code:p?.code||null,search_term:search_term?.slice(0,80)||null,session_id:sid(),page_path:location.pathname+location.search})}).catch(()=>{})}
function mediaUrl(m){if(!m)return'';const x=m.external_url||m.storage_path||'';if(/^https?:\/\//.test(x))return x;return x?BASE+'/storage/v1/object/public/'+BUCKET+'/'+x.split('/').map(encodeURIComponent).join('/'):''}
function mediaFor(id){const a=(data.media||[]).filter(m=>m.product_id===id&&m.is_visible!==false).sort((x,y)=>(x.sort_order||0)-(y.sort_order||0));const images=a.filter(m=>m.media_type!=='video');return{images,featured:images.find(m=>m.is_featured)||images[0]}}
function applyTheme(){const t=data.prefs?.theme||{};if(t.bg)document.documentElement.style.setProperty('--bg',t.bg);if(t.text)document.documentElement.style.setProperty('--text',t.text);if(t.muted)document.documentElement.style.setProperty('--muted',t.muted);if(t.accent)document.documentElement.style.setProperty('--gold',t.accent);if(t.accent2)document.documentElement.style.setProperty('--gold2',t.accent2)}
function hero(){const s=data.store||{},p=(data.products||[])[0],m=p?mediaFor(p.id).featured:null,u=mediaUrl(m);$('#watermark').textContent=s.watermark||'MODLAND.QESHM';$('#catalogTitle').textContent=s.catalog_title||s.store_name||'کاتالوگ مدلند';$('#tagline').textContent=s.tagline||'استایل خاص، انتخاب راحت، سفارش سریع';$('#countPill').textContent=fa(data.products.length)+' محصول';$('#shippingPill').textContent=s.footer_note||'ارسال رایگان';if(u){$('#heroImg').src=u;$('#heroImg').hidden=false}else $('#heroImg').hidden=true}
function chips(){const cats=(data.categories||[]).filter(c=>c.is_visible!==false);$('#chips').innerHTML=`<button class="chip ${activeCat===null?'on':''}" data-cat="">همه · ${fa(data.products.length)}</button>`+cats.map(c=>`<button class="chip ${activeCat===c.id?'on':''}" data-cat="${esc(c.id)}">${esc(c.name)} · ${fa(data.products.filter(p=>p.category_id===c.id).length)}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{activeCat=b.dataset.cat||null;chips();renderProducts()})}
function saved(){try{return new Set(JSON.parse(localStorage.getItem('modland_saved')||'[]'))}catch{return new Set()}}
function toggleSaved(p){const s=saved();s.has(p.id)?s.delete(p.id):s.add(p.id);localStorage.setItem('modland_saved',JSON.stringify([...s]));track('favorite',p);renderProducts()}
function renderProducts(){const q=term.trim().toLowerCase(),sv=saved();const arr=(data.products||[]).filter(p=>(!activeCat||p.category_id===activeCat)&&(!q||[p.name,p.code,p.brand,p.description,p.badge].filter(Boolean).some(v=>String(v).toLowerCase().includes(q))));$('#resultCount').textContent=fa(arr.length)+' مورد';$('#empty').hidden=arr.length>0;$('#grid').innerHTML=arr.map(p=>{const m=mediaFor(p.id).featured,u=mediaUrl(m),off=p.old_price_toman&&p.price_toman&&p.old_price_toman>p.price_toman?Math.round((1-p.price_toman/p.old_price_toman)*100):null;return `<article class="card"><a href="./product.html?code=${encodeURIComponent(p.code)}" aria-label="${esc(p.name)}"><div class="pic">${u?`<img src="${esc(u)}" alt="${esc(p.name)}" loading="lazy" decoding="async">`:'<div class="empty">بدون تصویر</div>'}${p.badge?`<span class="badge">${esc(p.badge)}</span>`:''}</div><div class="card-body"><div class="title">${esc(p.name)}</div><div class="sub">${esc(p.brand||'MODLAND')} · کد ${esc(p.code)}</div><div class="price">${money(p.price_toman)}${p.old_price_toman?` <span class="old">${money(p.old_price_toman)}</span>`:''}${off?` <small>٪${fa(off)}</small>`:''}</div></div></a><button class="fav ${sv.has(p.id)?'on':''}" data-fav="${p.id}" aria-label="علاقه‌مندی">♥</button></article>`}).join('');document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const p=data.products.find(x=>x.id===b.dataset.fav);if(p)toggleSaved(p)});requestAnimationFrame(()=>{const io=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){x.target.classList.add('reveal');io.unobserve(x.target)}}),{threshold:.05});document.querySelectorAll('.card').forEach(x=>io.observe(x))})}
function contacts(){const s=data.store||{};const links=[['اینستاگرام',s.instagram_url],['تلگرام',s.telegram_url],['روبیکا',s.rubika_url]].filter(x=>x[1]);$('#socials').innerHTML=links.map(([l,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener">${l}</a>`).join('');const phones=[['تماس ۱',s.phone1],['تماس ۲',s.phone2]].filter(x=>x[1]);if(phones.length||s.address){$('#contact').hidden=false;$('#phones').innerHTML=phones.map(([l,p])=>`<a class="phone" href="tel:${String(p).replace(/\s/g,'')}"><b>${esc(p)}</b><span>${l}</span></a>`).join('');$('#address').textContent=s.address||''}else $('#contact').hidden=true;$('#footerNote').textContent=s.footer_note||'';$('#storeName').textContent=s.store_name||''}
function renderAll(){applyTheme();hero();chips();renderProducts();contacts()}
function cacheRead(){try{const c=JSON.parse(localStorage.getItem(CACHE)||'null');if(c?.payload){data=c.payload;renderAll();$('#sync').textContent='نسخه ذخیره‌شده';return true}}catch{}return false}
function cacheWrite(payload){try{localStorage.setItem(CACHE,JSON.stringify({at:Date.now(),payload}))}catch{}}
async function fetchSnapshot(){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),8000);try{const r=await fetch(BASE+'/rest/v1/rpc/get_catalog_snapshot',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:'{}',cache:'no-store',signal:ctrl.signal});if(!r.ok)throw Error(await r.text());const d=await r.json();data={store:d.store||null,prefs:d.prefs||null,categories:d.categories||[],products:d.products||[],media:d.media||[]};cacheWrite(data);renderAll();$('#sync').textContent='به‌روز';$('#offline').classList.remove('show')}catch(e){if(!localStorage.getItem(CACHE)){$('#grid').innerHTML='<div class="empty" style="grid-column:1/-1">بارگذاری کاتالوگ انجام نشد. اتصال اینترنت را بررسی کنید و دوباره وارد شوید.</div>'}$('#sync').textContent='حالت ذخیره‌شده';$('#offline').classList.add('show')}finally{clearTimeout(timer)}}
let st;$('#q').addEventListener('input',e=>{term=e.target.value;renderProducts();clearTimeout(st);st=setTimeout(()=>{const q=term.trim();if(q.length>=2&&q!==lastTrackedSearch){lastTrackedSearch=q;track('search',null,q)}},700)});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#install').classList.add('show')});$('#install').onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#install').classList.remove('show')};
window.addEventListener('online',()=>{fetchSnapshot()});window.addEventListener('offline',()=>$('#offline').classList.add('show'));
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{});
const hadCache=cacheRead();if(!hadCache)renderAll();track('catalog_view');fetchSnapshot();