const BASE='https://bemkwibdtjrvrstlmvca.supabase.co',KEY='sb_publishable_oqpsHvl6ty2aYmAkxwfwfw_pjsN8a6p',BUCKET='modland-media',CACHE='modland_snapshot_v9',OLD_CACHES=[],SESSION='modland_anon_session';
let data={store:null,prefs:null,categories:[],products:[],media:[],collections:{new:[],popular:[],discounts:[],featured:[]}},product=null,currentImage=0,viewTracked=false;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),fa=n=>String(n??'').replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[+d]),money=n=>n==null?'تماس بگیرید':fa(Number(n).toLocaleString('en-US'))+' تومان';
function idle(fn){if('requestIdleCallback'in window)requestIdleCallback(fn,{timeout:1200});else setTimeout(fn,0)}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1900)}
function sid(){let s=localStorage.getItem(SESSION);if(!s){s=(crypto.randomUUID?.()||Math.random().toString(36).slice(2))+Date.now().toString(36);localStorage.setItem(SESSION,s)}return s.slice(0,80)}
function postJson(path,body){return fetch(BASE+path,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(body),keepalive:true})}
function track(event_type,p=null){idle(()=>postJson('/rest/v1/catalog_events',{event_type,product_id:p?.id||null,product_code:p?.code||null,session_id:sid(),page_path:location.pathname+location.search}).catch(()=>{}))}
function reportError(message,context={}){idle(()=>postJson('/rest/v1/rpc/report_app_error',{p_source:'product',p_message:String(message||'unknown error').slice(0,1000),p_context:context,p_session_id:sid()}).catch(()=>{}))}
window.addEventListener('error',e=>reportError(e.message,{file:e.filename?.split('/').pop(),line:e.lineno,col:e.colno}));
window.addEventListener('unhandledrejection',e=>reportError(e.reason?.message||String(e.reason||'unhandled rejection'),{type:'promise'}));
function mediaUrl(m){if(!m)return'';const x=m.external_url||m.storage_path||'';if(/^https?:\/\//i.test(x))return x;return x?BASE+'/storage/v1/object/public/'+BUCKET+'/'+x.split('/').map(encodeURIComponent).join('/'):''}
function mediaFor(id){const a=(data.media||[]).filter(m=>m.product_id===id&&m.is_visible!==false).sort((x,y)=>(x.sort_order||0)-(y.sort_order||0)||(String(x.id).localeCompare(String(y.id))));return{images:a.filter(m=>m.media_type!=='video'),videos:a.filter(m=>m.media_type==='video')}}
function applyTheme(){const t=data.prefs?.theme||{};if(t.bg)document.documentElement.style.setProperty('--bg',t.bg);if(t.text)document.documentElement.style.setProperty('--text',t.text);if(t.muted)document.documentElement.style.setProperty('--muted',t.muted);if(t.accent)document.documentElement.style.setProperty('--gold',t.accent);if(t.accent2)document.documentElement.style.setProperty('--gold2',t.accent2)}
function setMeta(){document.title=`${product.name} | MODLAND.QESHM`;const d=`${product.name}، کد ${product.code}، ${money(product.price_toman)} در کاتالوگ مدلند قشم.`;const m=document.querySelector('meta[name=description]');if(m)m.content=d}
function savedSet(){try{return new Set(JSON.parse(localStorage.getItem('modland_saved')||'[]'))}catch{return new Set()}}
function isSaved(){return product?savedSet().has(product.id):false}
function toggleSaved(){if(!product)return;const set=savedSet();set.has(product.id)?set.delete(product.id):set.add(product.id);localStorage.setItem('modland_saved',JSON.stringify([...set]));track('favorite',product);const b=$('#fav');if(b){b.textContent=set.has(product.id)?'♥':'♡';b.setAttribute('aria-pressed',String(set.has(product.id)))}toast('علاقه‌مندی به‌روزرسانی شد')}
function rankedRelated(){if(!product)return[];const c=data.collections||{},popular=c.popular||[],featured=new Set(c.featured||[]),newSet=new Set(c.new||[]),discounts=new Set(c.discounts||[]),popRank=new Map(popular.map((id,i)=>[id,i]));return(data.products||[]).filter(p=>p.id!==product.id).map(p=>{let score=0;if(product.category_id&&p.category_id===product.category_id)score+=5;if(product.brand&&p.brand&&product.brand.trim().toLowerCase()===p.brand.trim().toLowerCase())score+=3;const a=Number(product.price_toman||0),b=Number(p.price_toman||0);if(a>0&&b>0){const d=Math.abs(a-b)/a;if(d<=.15)score+=3;else if(d<=.35)score+=2;else if(d<=.6)score+=1}if(featured.has(p.id)||p.is_featured)score+=1.4;if(popRank.has(p.id))score+=Math.max(.4,1.6-popRank.get(p.id)*.18);if(newSet.has(p.id))score+=.35;if(discounts.has(p.id))score+=.25;return{p,score}}).sort((x,y)=>y.score-x.score||(x.p.sort_order||0)-(y.p.sort_order||0)||String(x.p.code).localeCompare(String(y.p.code))).slice(0,4).map(x=>x.p)}
function relatedHtml(){const related=rankedRelated();if(!related.length)return'';return `<section class="panel"><h3 style="font-size:13px;margin-top:0">پیشنهاد برای تو</h3><div class="related">${related.map(p=>{const mm=mediaFor(p.id).images,u=mediaUrl(mm.find(m=>m.is_featured)||mm[0]);return `<a class="r" href="./product.html?code=${encodeURIComponent(p.code)}">${u?`<img src="${esc(u)}" alt="${esc(p.name)}" loading="lazy" decoding="async">`:''}<div>${esc(p.name)}<br><b style="color:var(--gold2)">${money(p.price_toman)}</b></div></a>`}).join('')}</div></section>`}
function render(){if(!product)return;applyTheme();const s=data.store||{},mf=mediaFor(product.id),images=mf.images,videos=mf.videos,urls=images.map(mediaUrl),off=product.old_price_toman&&product.price_toman&&product.old_price_toman>product.price_toman?Math.round((1-product.price_toman/product.old_price_toman)*100):null;currentImage=Math.min(currentImage,Math.max(0,urls.length-1));const main=urls[currentImage]||'',shipping=String(s.footer_note||'ارسال رایگان به سراسر کشور'),wholesale=String(s.wholesale_note||'فقط فروش عمده');$('#root').innerHTML=`<div class="top"><a class="btn" href="./">→ کاتالوگ</a><div class="share"><button id="share" class="btn">اشتراک</button><button id="fav" class="btn" aria-pressed="${isSaved()}">${isSaved()?'♥':'♡'}</button></div></div>
<section class="gallery">${main?`<img id="mainImg" class="mainimg" src="${esc(main)}" alt="${esc(product.name)}" loading="eager" fetchpriority="high" decoding="async">`:`<div class="loading" style="min-height:420px">تصویری ثبت نشده</div>`}${urls.length>1?`<div class="thumbs">${urls.map((u,i)=>`<button class="thumb ${i===currentImage?'on':''}" data-img="${i}" aria-label="تصویر ${i+1}"><img src="${esc(u)}" alt="" loading="lazy" decoding="async"></button>`).join('')}</div>`:''}</section>
<section class="panel"><div class="eyebrow">${esc(s.watermark||'MODLAND.QESHM')}</div><h1 class="title">${esc(product.name)}</h1><div class="brand">${esc(product.brand||'MODLAND')} · کد ${esc(product.code)}</div><div class="pricing"><span class="price">${money(product.price_toman)}</span>${product.old_price_toman?`<span class="old">${money(product.old_price_toman)}</span>`:''}${off?`<span class="off">٪${fa(off)} تخفیف</span>`:''}</div><div class="meta">${product.badge?`<span class="tag">${esc(product.badge)}</span>`:''}<span class="tag" data-free-shipping>${esc(shipping)}</span><span class="tag" data-wholesale-only>${esc(wholesale)}</span></div></section>
${Array.isArray(product.sizes)&&product.sizes.length?`<section class="panel"><h3 style="font-size:13px;margin-top:0">سایزبندی</h3><div class="chips">${product.sizes.map(x=>`<span class="chip" aria-label="سایز ${esc(x)}">${esc(x)}</span>`).join('')}</div>${product.size_guide?`<div class="txt" style="margin-top:11px">${esc(product.size_guide)}</div>`:''}</section>`:''}
${product.description?`<section class="panel"><h3 style="font-size:13px;margin-top:0">جزئیات محصول</h3><div class="txt">${esc(product.description)}</div></section>`:''}
${Array.isArray(product.features)&&product.features.length?`<section class="panel"><h3 style="font-size:13px;margin-top:0">ویژگی‌ها</h3><ul class="features">${product.features.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`:''}
${videos.map(v=>`<video class="video" src="${esc(mediaUrl(v))}" controls playsinline preload="metadata"></video>`).join('')}
${relatedHtml()}`;document.querySelectorAll('[data-img]').forEach(b=>b.onclick=()=>{currentImage=+b.dataset.img;render()});const mi=$('#mainImg');if(mi)mi.onclick=()=>{$('#lbImg').src=mi.src;$('#lb').classList.add('show')};$('#share').onclick=shareProduct;$('#fav').onclick=toggleSaved}
async function copyText(text){try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return true}}catch{}try{const ta=document.createElement('textarea');ta.value=text;ta.setAttribute('readonly','');ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();return ok}catch{return false}}
async function shareProduct(){if(!product)return;const url=location.href;try{if(navigator.share)await navigator.share({title:product.name,text:`${product.name} | ${money(product.price_toman)}`,url});else if(await copyText(url))toast('لینک محصول کپی شد');else toast('کپی لینک انجام نشد')}catch(e){if(e?.name!=='AbortError')reportError(e.message,{stage:'share'})}track('share',product)}
async function fetchSnapshot(){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),6000);try{const r=await fetch(BASE+'/rest/v1/rpc/get_catalog_snapshot',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:'{}',cache:'no-store',signal:ctrl.signal});if(!r.ok)throw Error(await r.text());return await r.json()}finally{clearTimeout(timer)}}
function normalizeSnapshot(d){return{store:d?.store||null,prefs:d?.prefs||null,categories:d?.categories||[],products:d?.products||[],media:d?.media||[],collections:d?.collections||{new:[],popular:[],discounts:[],featured:[]}}}
function readCache(){for(const key of [CACHE,...OLD_CACHES]){try{const c=JSON.parse(localStorage.getItem(key)||'null');if(c?.payload)return normalizeSnapshot(c.payload)}catch{}}return null}
function writeCache(payload){try{localStorage.setItem(CACHE,JSON.stringify({at:Date.now(),payload}))}catch{}}
async function boot(){const code=new URLSearchParams(location.search).get('code');if(!code){$('#root').innerHTML='<div class="error">کد محصول مشخص نشده است.<br><br><a class="btn" href="./">بازگشت به کاتالوگ</a></div>';return}const cached=readCache();if(cached){data=cached;product=(data.products||[]).find(p=>String(p.code)===String(code));if(product){setMeta();render()}}try{const fresh=normalizeSnapshot(await fetchSnapshot());data=fresh;writeCache(data);product=(data.products||[]).find(p=>String(p.code)===String(code));if(!product)throw Error('not found');setMeta();render();if(!viewTracked){viewTracked=true;track('product_view',product)}}catch(e){if(!product){$('#root').innerHTML='<div class="error">این محصول پیدا نشد یا در حال حاضر منتشر نشده است.<br><br><a class="btn" href="./">بازگشت به کاتالوگ</a></div>'}reportError(e.message,{stage:'snapshot',online:navigator.onLine})}}
$('#lbClose').onclick=()=>$('#lb').classList.remove('show');$('#lb').onclick=e=>{if(e.target.id==='lb')$('#lb').classList.remove('show')};document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#lb').classList.remove('show')});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(e=>reportError(e.message,{stage:'sw'}));boot();