const BASE='https://bemkwibdtjrvrstlmvca.supabase.co',KEY='sb_publishable_oqpsHvl6ty2aYmAkxwfwfw_pjsN8a6p',BUCKET='modland-media',CACHE='modland_snapshot_v6',SESSION='modland_anon_session';
let data={store:null,prefs:null,categories:[],products:[],media:[]},product=null,selectedSize=null,currentImage=0;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),fa=n=>String(n??'').replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[+d]),money=n=>n==null?'تماس بگیرید':fa(Number(n).toLocaleString('en-US'))+' تومان';
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
function sid(){let s=localStorage.getItem(SESSION);if(!s){s=(crypto.randomUUID?.()||Math.random().toString(36).slice(2))+Date.now().toString(36);localStorage.setItem(SESSION,s)}return s.slice(0,80)}
function track(event_type,p=null){fetch(BASE+'/rest/v1/catalog_events',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({event_type,product_id:p?.id||null,product_code:p?.code||null,session_id:sid(),page_path:location.pathname+location.search})}).catch(()=>{})}
function mediaUrl(m){if(!m)return'';const x=m.external_url||m.storage_path||'';if(/^https?:\/\//.test(x))return x;return x?BASE+'/storage/v1/object/public/'+BUCKET+'/'+x.split('/').map(encodeURIComponent).join('/'):''}
function mediaFor(id){const a=(data.media||[]).filter(m=>m.product_id===id&&m.is_visible!==false).sort((x,y)=>(x.sort_order||0)-(y.sort_order||0));return{images:a.filter(m=>m.media_type!=='video'),videos:a.filter(m=>m.media_type==='video')}}
function orderUser(){const o=(data.store?.order_id||'').trim();if(o.startsWith('@'))return o.slice(1);if(/^https?:\/\/t\.me\//i.test(o))return o.replace(/^https?:\/\/t\.me\//i,'').split(/[/?#]/)[0];return''}
function orderText(){const base=product.order_message||`سلام، برای ${product.name} کد ${product.code} پیام می‌دهم.`;return selectedSize?base+` سایز ${selectedSize}.`:base}
function orderUrl(){const u=orderUser();return u?'https://t.me/'+encodeURIComponent(u)+'?text='+encodeURIComponent(orderText()):(data.store?.telegram_url||'#')}
function updateOrder(){if(!product)return;$('#order').href=orderUrl()}
function setMeta(){document.title=`${product.name} | MODLAND.QESHM`;const d=`${product.name}، کد ${product.code}، ${money(product.price_toman)} در فروشگاه مدلند قشم.`;let m=document.querySelector('meta[name=description]');if(m)m.content=d}
function render(){const s=data.store||{},mf=mediaFor(product.id),images=mf.images,videos=mf.videos,urls=images.map(mediaUrl),off=product.old_price_toman&&product.price_toman&&product.old_price_toman>product.price_toman?Math.round((1-product.price_toman/product.old_price_toman)*100):null,related=(data.products||[]).filter(p=>p.id!==product.id&&(!product.category_id||p.category_id===product.category_id)).slice(0,3);const main=urls[currentImage]||urls[0]||'';$('#root').innerHTML=`<div class="top"><a class="btn" href="./">→ کاتالوگ</a><div class="share"><button id="share" class="btn">اشتراک</button><button id="fav" class="btn">♡</button></div></div>
<section class="gallery">${main?`<img id="mainImg" class="mainimg" src="${esc(main)}" alt="${esc(product.name)}" decoding="async">`:`<div class="loading" style="min-height:420px">تصویری ثبت نشده</div>`}${urls.length>1?`<div class="thumbs">${urls.map((u,i)=>`<button class="thumb ${i===currentImage?'on':''}" data-img="${i}"><img src="${esc(u)}" alt="" loading="lazy"></button>`).join('')}</div>`:''}</section>
<section class="panel"><div class="eyebrow">${esc(s.watermark||'MODLAND.QESHM')}</div><h1 class="title">${esc(product.name)}</h1><div class="brand">${esc(product.brand||'MODLAND')} · کد ${esc(product.code)}</div><div class="pricing"><span class="price">${money(product.price_toman)}</span>${product.old_price_toman?`<span class="old">${money(product.old_price_toman)}</span>`:''}${off?`<span class="off">٪${fa(off)} تخفیف</span>`:''}</div><div class="meta">${product.stock_status?`<span class="tag">${esc(product.stock_status)}</span>`:''}${product.badge?`<span class="tag">${esc(product.badge)}</span>`:''}${product.shipping_text?`<span class="tag">${esc(product.shipping_text)}</span>`:''}</div>${product.stock_note?`<div class="txt" style="margin-top:10px">${esc(product.stock_note)}</div>`:''}</section>
${product.sizes?.length?`<section class="panel"><h3 style="font-size:13px;margin-top:0">انتخاب سایز</h3><div class="chips">${product.sizes.map(x=>`<button class="chip ${selectedSize===x?'on':''}" data-size="${esc(x)}">${esc(x)}</button>`).join('')}</div>${product.size_guide?`<div class="txt" style="margin-top:11px">${esc(product.size_guide)}</div>`:''}</section>`:''}
${product.description?`<section class="panel"><h3 style="font-size:13px;margin-top:0">جزئیات محصول</h3><div class="txt">${esc(product.description)}</div></section>`:''}
${product.features?.length?`<section class="panel"><h3 style="font-size:13px;margin-top:0">ویژگی‌ها</h3><ul class="features">${product.features.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`:''}
${videos.map(v=>`<video class="video" src="${esc(mediaUrl(v))}" controls playsinline preload="metadata"></video>`).join('')}
${related.length?`<section class="panel"><h3 style="font-size:13px;margin-top:0">محصولات مشابه</h3><div class="related">${related.map(p=>{const u=mediaUrl(mediaFor(p.id).images[0]);return `<a class="r" href="./product.html?code=${encodeURIComponent(p.code)}">${u?`<img src="${esc(u)}" alt="${esc(p.name)}" loading="lazy">`:''}<div>${esc(p.name)}<br><b style="color:var(--gold2)">${money(p.price_toman)}</b></div></a>`}).join('')}</div></section>`:''}`;document.querySelectorAll('[data-img]').forEach(b=>b.onclick=()=>{currentImage=+b.dataset.img;render()});document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{selectedSize=selectedSize===b.dataset.size?null:b.dataset.size;render();updateOrder()});const mi=$('#mainImg');if(mi)mi.onclick=()=>{$('#lbImg').src=mi.src;$('#lb').classList.add('show')};$('#share').onclick=async()=>{const url=location.href;try{if(navigator.share)await navigator.share({title:product.name,text:`${product.name} | ${money(product.price_toman)}`,url});else{await navigator.clipboard.writeText(url);toast('لینک محصول کپی شد')}}catch{}track('share',product)};$('#fav').onclick=()=>{let a=[];try{a=JSON.parse(localStorage.getItem('modland_saved')||'[]')}catch{}const set=new Set(a);set.has(product.id)?set.delete(product.id):set.add(product.id);localStorage.setItem('modland_saved',JSON.stringify([...set]));track('favorite',product);toast('علاقه‌مندی به‌روزرسانی شد')};$('#sticky').hidden=false;updateOrder()}
async function fetchSnapshot(){const r=await fetch(BASE+'/rest/v1/rpc/get_catalog_snapshot',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:'{}',cache:'no-store'});if(!r.ok)throw Error(await r.text());return r.json()}
async function boot(){const code=new URLSearchParams(location.search).get('code');if(!code){$('#root').innerHTML='<div class="error">کد محصول مشخص نشده است.<br><br><a class="btn" href="./">بازگشت به کاتالوگ</a></div>';return}try{let cached=null;try{cached=JSON.parse(localStorage.getItem(CACHE)||'null')?.payload}catch{}if(cached){data=cached;product=(data.products||[]).find(p=>String(p.code)===String(code));if(product){setMeta();render()}}const fresh=await fetchSnapshot();data={store:fresh.store||null,prefs:fresh.prefs||null,categories:fresh.categories||[],products:fresh.products||[],media:fresh.media||[]};try{localStorage.setItem(CACHE,JSON.stringify({at:Date.now(),payload:data}))}catch{}product=(data.products||[]).find(p=>String(p.code)===String(code));if(!product)throw Error('not found');setMeta();render();track('product_view',product)}catch(e){if(!product)$('#root').innerHTML='<div class="error">این محصول پیدا نشد یا در حال حاضر منتشر نشده است.<br><br><a class="btn" href="./">بازگشت به کاتالوگ</a></div>'}}
$('#order').onclick=()=>{if(product)track('order_click',product)};$('#copyOrder').onclick=async()=>{if(!product)return;await navigator.clipboard.writeText(orderText());toast('متن سفارش کپی شد')};$('#lbClose').onclick=()=>$('#lb').classList.remove('show');$('#lb').onclick=e=>{if(e.target.id==='lb')$('#lb').classList.remove('show')};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{});boot();